# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Inf < Formula
  desc "infinimesh Platform CLI"
  homepage "https://github.com/infinimesh/infinimesh"
  version "3.0.0-r10"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/infinimesh/inf/releases/download/v3.0.0-r10/inf_3.0.0-r10_Darwin_arm64.tar.gz"
      sha256 "58fe9a84791d1f241b7396cf78c617a9ec088f679c3439e0958a4d6c754c2b63"

      def install
        bin.install "inf"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/infinimesh/inf/releases/download/v3.0.0-r10/inf_3.0.0-r10_Darwin_x86_64.tar.gz"
      sha256 "c09da2717959d6fcf2ef9dd42e889e942f17919b1d81c276a8b2ca90d78df342"

      def install
        bin.install "inf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/infinimesh/inf/releases/download/v3.0.0-r10/inf_3.0.0-r10_Linux_arm64.tar.gz"
      sha256 "cb7ca7b398eded9e6c887a3c4b452afd4ce263ad84c18da59ea6f83cdb526b69"

      def install
        bin.install "inf"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/infinimesh/inf/releases/download/v3.0.0-r10/inf_3.0.0-r10_Linux_x86_64.tar.gz"
      sha256 "0952ae87247cd2bd36b20d076a0b5277288c1af2df5cb7804cedcf1356dade2d"

      def install
        bin.install "inf"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/infinimesh/inf/releases/download/v3.0.0-r10/inf_3.0.0-r10_Linux_arm.tar.gz"
      sha256 "71edc1da0c24b67069ffae80227b62c942e2a5f1a6ef48968ff231f88356b664"

      def install
        bin.install "inf"
      end
    end
  end

  def caveats; <<~EOS
    Start with inf help login ;)
  EOS
  end
end
