# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Inf < Formula
  desc "infinimesh Platform CLI"
  homepage "https://github.com/infinimesh/infinimesh"
  version "3.0.0-r20"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/infinimesh/inf/releases/download/v3.0.0-r20/inf_3.0.0-r20_Darwin_arm64.tar.gz"
      sha256 "8972dc741d4ed73c18e5a00aaf1e607c6d98a007c09731be16464e6598a9571f"

      def install
        bin.install "inf"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/infinimesh/inf/releases/download/v3.0.0-r20/inf_3.0.0-r20_Darwin_x86_64.tar.gz"
      sha256 "8054a96061bc97c26e4d149c8d8dc789a69e518f4953b5c7f466af146b992ecf"

      def install
        bin.install "inf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/infinimesh/inf/releases/download/v3.0.0-r20/inf_3.0.0-r20_Linux_arm64.tar.gz"
      sha256 "50a9cf348f920f94d1ba2a0ece303ed84fe7a585a2f25f0ef5223a5f17b07aa6"

      def install
        bin.install "inf"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/infinimesh/inf/releases/download/v3.0.0-r20/inf_3.0.0-r20_Linux_x86_64.tar.gz"
      sha256 "20b141dee37208bfcab76e0f3df1b0f2f13b8a56f6c15e3eba734028fb6f894f"

      def install
        bin.install "inf"
      end
    end
  end

  def caveats
    <<~EOS
      Start with inf help login ;)
    EOS
  end
end
